apps/books/urls.py
from django.urls import path

from . import views

app_name = 'books'

urlpatterns = [
    path('', views.BooksListView.as_view(), name='list'),
    path('logging/', views.BooksLoggingView.as_view(), name='logging'),
    path('create/', views.CreateBookView.as_view(), name='create'),
    path('<pk>/', views.UpdateBookView.as_view(), name='update'),
    path('<pk>/delete/', views.DeleteBookView.as_view(), name='delete')
]

apps/request_logging/urls.py
from django.urls import path

from . import views

app_name = 'request_logging'

urlpatterns = [
    path('', views.RequestsListView.as_view(), name='list'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include('books.urls')),
    path('requests-logging/', include('request_logging.urls')),
]

apps/books/models.py
from django.utils import timezone
from django.db import models
from django.db.models import DateField


class Books(models.Model):
    title = models.CharField(max_length=80)
    authors_info = models.CharField(max_length=100)
    isbn = models.CharField(max_length=20)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    publish_date = DateField(default=timezone.now)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        manipulation_type = 'update' if self.pk else 'create'
        BooksLogging.objects.create(manipulation_type=manipulation_type, book_title=self.title)
        super(Books, self).save(force_insert, force_update, using, update_fields)

    def delete(self, using=None, keep_parents=False):
        BooksLogging.objects.create(manipulation_type='delete', book_title=self.title)
        super(Books, self).delete(using, keep_parents)

    class Meta:
        db_table = 'books'


class BooksLogging(models.Model):
    manipulation_type = models.CharField(max_length=10)
    book_title = models.CharField(max_length=80, null=True, blank=True)
    time = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'books_logging'

apps/request_logging/models.py
from django.db import models


class RequestRequest(models.Model):
    response = models.SmallIntegerField()
    method = models.CharField(max_length=7)
    path = models.CharField(max_length=255)
    time = models.DateTimeField()
    is_secure = models.BooleanField()
    is_ajax = models.BooleanField()
    ip = models.GenericIPAddressField()
    referer = models.CharField(max_length=255, blank=True, null=True)
    user_agent = models.CharField(max_length=255, blank=True, null=True)
    language = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'request_request'

apps/books/forms.py
from django import forms

from books.models import Books


class BooksForm(forms.ModelForm):
    required_css_class = 'error'

    class Meta:
        model = Books
        fields = ['title', 'authors_info', 'isbn', 'publish_date', 'price']

apps/books/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from books.forms import BooksForm
from books.models import Books, BooksLogging


class BooksListView(ListView):
    model = Books
    template_name = 'books/books_list.html'
    ordering = '-publish_date'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ordering'] = self.get_ordering()
        return context

    def get_ordering(self):
        if 'ordering' in self.request.GET.keys():
            self.ordering = 'publish_date' if self.request.GET['ordering'].startswith('-') else '-publish_date'
        return self.ordering


class CreateBookView(CreateView):
    model = Books
    form_class = BooksForm
    template_name = 'books/create_book.html'
    success_url = reverse_lazy('books:list')


class UpdateBookView(UpdateView):
    model = Books
    form_class = BooksForm
    template_name = 'books/update_book.html'
    success_url = reverse_lazy('books:list')


class DeleteBookView(DeleteView):
    model = Books
    success_url = reverse_lazy('books:list')


class BooksLoggingView(ListView):
    model = BooksLogging
    template_name = 'books/books_logging_list.html'

apps/request_logging/views.py
from django.views.generic import ListView

from request_logging.models import RequestRequest


class RequestsListView(ListView):
    model = RequestRequest
    template_name = 'requests_logging/requests_list.html'
    paginate_by = 10
    ordering = '-time'

apps/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block head %}
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    {% endblock %}
    <style>
        footer {
            position:fixed;
            left:0px;
            bottom:0px;
            height:30px;
            width:100%;
        }
    </style>
</head>

<body class="pace-done">
<div class="container-fluid">
    <div class="row">
        <div class="col-md-offset-1">
            <br>
            <a class="btn btn-default" href="{% url 'books:list' %}">*Books</a>
            <a class="btn btn-default" href="{% url 'books:logging' %}">*Books Logging</a>
            <a class="btn btn-default" href="{% url 'request_logging:list' %}">*Requests Logging</a>
            <a class="btn btn-default" href="{% url 'admin:index' %}">*Admin Panel</a>
            <br><br>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="wrapper wrapper-content">
                {% block content %}{% endblock %}
            </div>
            <footer class="footer">
                <div class="pull-right">
                    Created By <a href="#" target="_blank">Viktor Volchanskiy</a>
                </div>
                <div>
                    <strong>Copyright</strong> VikVV &copy; 2016-{% now "Y" %}
                </div>
            </footer>
        </div>
    </div>
</div>
</body>
</html>

apps/templates/books/books_list.html
{% extends 'base.html' %}


{% block title %}Books{% endblock %}
{% block content %}
    <div class="wrapper wrapper-content">
        <div class="row">
            <div class="col-md-offset-1 col-md-3">
                <a href="{% url 'books:create' %}" class="btn btn-primary">Create Book</a>
            </div>
            <br>
            <br>
            <div class="col-md-offset-1 col-md-10">
                <table class="table table-striped table-bordered table-hover" >
                    <thead>
                    <tr>
                        <td class="text-center" style="background-color: #f8f8f8; font-weight: bold;">Title</td>
                        <td class="text-center" style="background-color: #f8f8f8; font-weight: bold;">Authors info</td>
                        <td class="text-center" style="background-color: #f8f8f8; font-weight: bold;">ISBN</td>
                        <td class="text-center" style="background-color: #f8f8f8; font-weight: bold;">
                            <a href="{% url 'books:list' %}?ordering={{ ordering }}">Publish Date</a>
                        </td>
                        <td class="text-center" style="background-color: #f8f8f8; font-weight: bold;">Price</td>
                        <td class="text-center" style="background-color: #f8f8f8; font-weight: bold;">Action</td>
                    </tr>
                    </thead>
                    <tbody>
                    {% for book in object_list %}
                        <tr>
                            <td class="text-center">{{ book.title }}</td>
                            <td class="text-center">{{ book.authors_info }}</td>
                            <td class="text-center">{{ book.isbn }}</td>
                            <td class="text-center">{{ book.publish_date }}</td>
                            <td class="text-center">{{ book.price }}</td>
                            <td class="text-center">
                                <a class="btn btn-default" href="{% url 'books:update' pk=book.pk %}">Edit</a>
                                <form method="post" action="{% url 'books:delete' pk=book.pk %}">
                                    {% csrf_token %}
                                    <input class="btn btn-danger" type="submit" value="Delete">
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

apps/templates/books/books_logging_list.html
{% extends 'base.html' %}


{% block title %}Books Logging{% endblock %}
{% block content %}
    <div class="wrapper wrapper-content">
        <div class="row">
            <div class="col-md-offset-1 col-md-10">
                <table class="table table-striped table-bordered table-hover" >
                    <thead>
                    <tr>
                        <td class="text-center" style="background-color: #f8f8f8; font-weight: bold;">Book</td>
                        <td class="text-center" style="background-color: #f8f8f8; font-weight: bold;">Type</td>
                        <td class="text-center" style="background-color: #f8f8f8; font-weight: bold;">Time</td>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in object_list %}
                        <tr>
                            <td class="text-center">{{ item.book_title }}</td>
                            <td class="text-center">{{ item.manipulation_type }}</td>
                            <td class="text-center">{{ item.time }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

apps/templates/books/create_book.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Books{% endblock %}
{% block content %}
    <style>
        .error {
            color: red;
        }
    </style>
    {% with 'new_book' as form_id %}
        <form id="{{ form_id }}"
              class="important-form"
              role="form"
              method="post"
              action="{% block action_url %}{% url 'books:create' %}{% endblock %}"
        >
            {% csrf_token %}
        </form>
        <div class="row">
            {{ form.non_field_errors }}
            <div class="col-md-offset-4 col-md-4">
                <div class="form-group">
                    <label>Title</label>
                    <input type="text"
                           name="{{ form.title.html_name }}"
                           form="{{ form_id }}"
                           class="form-control"
                           value="{% firstof form.title.value '' %}">
                    {% for error in form.title.errors %}
                        <span class="error help-block">{{ error }}</span>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-offset-4 col-md-4">
                <div class="form-group">
                    <label>Authors info</label>
                    <input type="text"
                           name="{{ form.authors_info.html_name }}"
                           form="{{ form_id }}"
                           class="form-control"
                           value="{% firstof form.authors_info.value '' %}">
                    {% for error in form.authors_info.errors %}
                        <span class="error help-block">{{ error }}</span>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-offset-4 col-md-4">
                <div class="form-group">
                    <label>ISBN</label>
                    <input type="text"
                           name="{{ form.isbn.html_name }}"
                           form="{{ form_id }}"
                           class="form-control"
                           value="{% firstof form.isbn.value '' %}">
                    {% for error in form.isbn.errors %}
                        <span class="error help-block">{{ error }}</span>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-offset-4 col-md-4">
                <div class="form-group">
                    <label>Publish date</label>
                    <input type="date"
                           name="{{ form.publish_date.html_name }}"
                           form="{{ form_id }}"
                           class="form-control"
                           value="{% firstof form.publish_date.value|date:'Y-m-d' '' %}">
                    {% for error in form.publish_date.errors %}
                        <span class="error help-block">{{ error }}</span>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-offset-4 col-md-4">
                <div class="form-group">
                    <label>Price</label>
                    <input type="number"
                           name="{{ form.price.html_name }}"
                           form="{{ form_id }}"
                           class="form-control"
                           value="{% firstof form.price.value '' %}">
                    {% for error in form.price.errors %}
                        <span class="error help-block">{{ error }}</span>
                    {% endfor %}
                </div>
            </div>
        </div>
         <div class="row">
            <div class="col-md-offset-4 col-md-4">
                {% block form_submit_buttons %}
                    <button type="submit" form="{{ form_id }}" class="btn btn-primary">Save</button>
                    <a href="{% url 'books:list'  %}" class="btn btn-danger">Cancel</a>
                {% endblock %}
            </div>
        </div>
    {% endwith %}
{% endblock %}

apps/templates/books/update_book.html
{% extends 'books/create_book.html' %}

{% block action_url %}{% url 'books:update' pk=object.id %}{% endblock %}

{% block form_submit_buttons %}
    {{ block.super }}
{% endblock %}
{% block add_suppliers %}{% endblock %}

apps/templates/requests_logging/requests_list.html
{% extends 'base.html' %}


{% block title %}Requests{% endblock %}
{% block content %}
    <div class="wrapper wrapper-content">
        <div class="row">
            <br>
            <br>
            <div class="col-md-offset-1 col-md-10">
                <table class="table table-striped table-bordered table-hover" >
                    <thead>
                    <tr>
                        <td class="text-center" style="background-color: #f8f8f8; font-weight: bold;">Response</td>
                        <td class="text-center" style="background-color: #f8f8f8; font-weight: bold;">Method</td>
                        <td class="text-center" style="background-color: #f8f8f8; font-weight: bold;">Path</td>
                        <td class="text-center" style="background-color: #f8f8f8; font-weight: bold;">Time</td>
                        <td class="text-center" style="background-color: #f8f8f8; font-weight: bold;">Is secure</td>
                        <td class="text-center" style="background-color: #f8f8f8; font-weight: bold;">Is ajax</td>
                        <td class="text-center" style="background-color: #f8f8f8; font-weight: bold;">IP</td>
                        <td class="text-center" style="background-color: #f8f8f8; font-weight: bold;">Referer</td>
                        <td class="text-center" style="background-color: #f8f8f8; font-weight: bold;">User agent</td>
                        <td class="text-center" style="background-color: #f8f8f8; font-weight: bold;">Language</td>
                    </tr>
                    </thead>
                    <tbody>
                    {% for request in object_list %}
                        <tr>
                            <td class="text-center">{{ request.response }}</td>
                            <td class="text-center">{{ request.method }}</td>
                            <td class="text-center">{{ request.path }}</td>
                            <td class="text-center">{{ request.time }}</td>
                            <td class="text-center">{{ request.is_secure }}</td>
                            <td class="text-center">{{ request.is_ajax }}</td>
                            <td class="text-center">{{ request.ip }}</td>
                            <td class="text-center">{{ request.referer }}</td>
                            <td class="text-center">{{ request.user_agent }}</td>
                            <td class="text-center">{{ request.language }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}